version: '3.8'
services:
  webapi:
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db
      - rabbitmq

  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"   # Порт для RabbitMQ
      - "15672:15672" # Порт для веб-интерфейса RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest